### ISSUE TITLE
'makeslice: len out of range' panic in mergeStoredAndRemap()

### ISSUE THREAD

**Issue by x1sec** [zincsearch/zincsearch#553]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
Fetch data, using S3 as the backend.

**What action did you take?**
Query data, no filter, all time via ZincSearch

**What action/response/output did you expect?**
Documents to be returned

**What actually happened?**
Process crashed with the following:
...
```
{"level":"debug","time":"2022-09-26T07:41:15+10:00","message":"Load: s3 GetObject call made. s3://test/test11/1RZoeJmHyeI/000000/00000001500f.seg"}
{"level":"debug","time":"2022-09-26T07:41:16+10:00","message":"List: s3 ListObjectsV2 call made for: s3://test/test1/1RZoeJmHyeI/000000"}
{"level":"debug","time":"2022-09-26T07:41:16+10:00","message":"Stats: s3 ListObjectsV2 call made for Stats"}
panic: runtime error: makeslice: len out of range

goroutine 88 [running]:
github.com/blugelabs/ice.mergeStoredAndRemap({0x14000744020, 0x1, 0x14000490210?}, {0x14000744018, 0x1, 0x0?}, 0x1053368c0?, {0x14000644360, 0x9, 0x9}, ...)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:654 +0xe4
github.com/blugelabs/ice.mergeToWriter({0x14000744020?, 0x1, 0x1}, {0x14000744018, 0x1, 0x1}, 0x88000?, 0x14000744020?, 0x0?)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:133 +0x130
github.com/blugelabs/ice.mergeSegmentBasesWriter({0x14000744020, 0x1, 0x1}, {0x14000744018, 0x1, 0x1}, {0x10406f138?, 0x1400004b640}, 0x401, 0x100f2add8?)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:97 +0xb8
github.com/blugelabs/ice.merge({0x140004eaa20, 0x1, 0x7948?}, {0x14000744018, 0x1, 0x1}, {0x10406f138, 0x1400004b640}, 0x0?)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:86 +0x84
github.com/blugelabs/ice.(*Merger).WriteTo(0x14000484c30, {0x10406f178?, 0x14000746120?}, 0x140006442d0?)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:49 +0x14c
github.com/zinclabs/zinc/pkg/bluge/directory.(*S3Directory).Persist(0x1400002a660, {0x101757db7, 0x4}, 0x14000744018?, {0x12c877fc0, 0x14000484c30}, 0x100000?)
	/codebuild/output/src383838028/src/github.com/zinclabs/zinc/pkg/bluge/directory/s3.go:163 +0x74
github.com/blugelabs/bluge/index.(*Writer).merge(0x14000071200, {0x140004eaa20?, 0x140007b7c88?, 0x100968670?}, {0x14000744018?, 0x10532c388?, 0x140007b7c38?}, 0x14?)
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/index/merge.go:368 +0xac
github.com/blugelabs/bluge/index.(*Writer).executeMergeTask(0x14000071200, 0x140004aa5a0, 0x140000ae4e0)
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/index/merge.go:144 +0x1a8
github.com/blugelabs/bluge/index.(*Writer).planMergeAtSnapshot(0x14000071200, 0x1400006eec8?, 0x140003ee380, {0xa, 0xf4240, 0x4024000000000000, 0xa, 0x7d0, 0x4000000000000000, 0x0, ...})
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/index/merge.go:118 +0x394
github.com/blugelabs/bluge/index.(*Writer).mergerLoop(0x14000071200, 0x1009c6f74?, 0x14000964ba0?)
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/index/merge.go:56 +0x1dc
created by github.com/blugelabs/bluge/index.OpenWriter
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/index/writer.go:131 +0x72c
```

**How to reproduce the issue?**
I can reproduce it with my dataset each time attempting to fetch data. Unable to query the Zinc without this crash.

**What version of ZincSearch are you using?**
0.3.2

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
Possibly corruption occurred with an unclean process termination earlier, but unsure.

**Any attachments/screenshots?**
See stack trace above.

**Which service(s) is this relate to?**
bluge ?

**Comment by prabhatsharma** [comment]
I would recommend against using s3 for now as its not ready for prime time.

**Comment by prabhatsharma** [comment]
s3 support has been deprecated
