### ISSUE TITLE
build docker image failed

### ISSUE THREAD

**Issue by ixlm** [zincsearch/zincsearch#854]
it gives me some errors when i build the zinc v0.4.3 docker image.
```
 > [webbuilder 5/5] RUN npm run build:                                                                                                                                
#0 2.013                                                                                                                                                              
#0 2.013 > zinc-search@0.3.6 build /web                                                                                                                               
#0 2.013 > vue-tsc --noEmit && vite build                                                                                                                             
#0 2.013                                                                                                                                                              
#0 7.909 (node:26) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
#0 7.928 failed to load config from /web/vite.config.ts
#0 7.928 error during build:
#0 7.928 /web/node_modules/@quasar/vite-plugin/dist/index.js:272
#0 7.928     ext => filename?.endsWith(ext) || query?.[`lang${ext}`] !== void 0
#0 7.928                     ^
#0 7.928 
#0 7.928 SyntaxError: Unexpected token '.'
#0 7.928     at wrapSafe (internal/modules/cjs/loader.js:1067:16)
#0 7.928     at Module._compile (internal/modules/cjs/loader.js:1115:27)
#0 7.928     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
#0 7.928     at Module.load (internal/modules/cjs/loader.js:1000:32)
#0 7.928     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
#0 7.928     at Module.require (internal/modules/cjs/loader.js:1040:19)
#0 7.928     at require (internal/modules/cjs/helpers.js:72:18)
#0 7.928     at Object.<anonymous> (/web/vite.config.ts:30:26)
#0 7.928     at Module._compile (internal/modules/cjs/loader.js:1151:30)
#0 7.928     at Object.require.extensions.<computed> [as .ts] (/web/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61998:20)
#0 7.931 npm ERR! code ELIFECYCLE
#0 7.931 npm ERR! errno 1
#0 7.932 npm ERR! zinc-search@0.3.6 build: `vue-tsc --noEmit && vite build`
#0 7.932 npm ERR! Exit status 1
#0 7.932 npm ERR! 
#0 7.932 npm ERR! Failed at the zinc-search@0.3.6 build script.
#0 7.932 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#0 7.982 
#0 7.982 npm ERR! A complete log of this run can be found in:
#0 7.982 npm ERR!     /root/.npm/_logs/2023-04-04T08_40_16_913Z-debug.log
```
my os is ubuntu 22.04 server version. how to fix it.

**Comment by gaby** [comment]
@ixlm Why not use the published image? There's no need to build it yourself.

**Comment by hengfeiyang** [comment]
Which Dockerfile do you use?

**Comment by ixlm** [comment]
Dockerfile just under the project root directory! @hengfeiyang

**Comment by ixlm** [comment]
there're 3 docker files (Dockerfile, Dockerfile.ci, Dockerfile.hub),  what're the differences between these files!  how do you build the docker image? @hengfeiyang

**Comment by ixlm** [comment]
thank you , i finish to build the docker image by change the Dockerfile like this.
change the original code 
```
# syntax=docker/dockerfile:experimental
############################
# STEP 1 build web dist
############################
FROM node:13.8.0-slim as webBuilder
```
to
```
# syntax=docker/dockerfile:experimental
############################
# STEP 1 build web dist
############################
FROM node:14.18.3-slim as webBuilder
```
, it's just an error about version of nodejs

**Comment by hengfeiyang** [comment]
I will update the dockerfile, maybe you can contribute a pr for this?

**Comment by gaby** [comment]
@hengfeiyang Current LTS is Node 18, but upgrading Zinc to that will probably break some stuff.

https://github.com/nodejs/release#release-schedule

**Comment by hengfeiyang** [comment]
updated dockerfiles

**Comment by gaby** [comment]
@hengfeiyang Thank you! Lots of changes, any plans to release v0.5.0 ?
